export const ADD_MACHINES = 'ADD_MACHINES';
export const SELECT_MACHINE = "SELECT_MACHINE";
export const ADD_APP_TO_MACHINE = "ADD_APP";
export const ADD_SEAL_APPS = "ADD_SEAL_APPS";
export const REMOVE_SEAL_APPS_FROM_MACHINE = "REMOVE_SEAL_APPS_FROM_MACHINE";